"""empty message

Revision ID: a3b682d09fd5
Revises: 9d2fbeaf7cd1
Create Date: 2024-06-10 21:18:57.845525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b682d09fd5'
down_revision = '9d2fbeaf7cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_filename', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_filename')
    # ### end Alembic commands ###
